# Streamlit Cloud Secrets Template
# Add your secrets in the Streamlit Cloud dashboard

GEMINI_API_KEY = "your_gemini_api_key_here"

# Note: Add actual API key in Streamlit Cloud Secrets management
# Go to: https://share.streamlit.io → Your App → Settings → Secrets
